"""empty message

Revision ID: 2d5df0474e07
Revises: 83d3428d2b61
Create Date: 2025-01-09 13:06:22.688150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5df0474e07'
down_revision = '83d3428d2b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.Enum('stock_focus', 'stock_community', 'financial_news'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
