"""remove likes dislikes and favorites

Revision ID: 8a21ec26469f
Revises: 7d5e2ed90db3
Create Date: 2025-01-11 19:03:28.446411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a21ec26469f'
down_revision = '7d5e2ed90db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')
        batch_op.drop_column('favorites')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislikes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('likes', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('likes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dislikes', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
