"""empty message

Revision ID: c473f48e9b48
Revises: 8945586ab681
Create Date: 2025-01-11 16:30:10.143196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c473f48e9b48'
down_revision = '8945586ab681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('section',
               existing_type=mysql.ENUM('stock_focus', 'stock_community', 'financial_news'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('stock_focus', 'stock_community', 'financial_news'),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
